export { default as DictCascader } from './cascader.vue'
export { default as DictCheckbox } from './checkbox.vue'
export { default as DictRadio } from './radio.vue'
export { default as DictSelect } from './select.vue'
export { default as DictSwitch } from './switch.vue'
export { default as DictText } from './text.vue'
export { default as DictTreeSelect } from './tree-select.vue'
